import type { Metadata } from "next";
import "./globals.css";
import Background from "../components/background";
import Navbar from "../components/navbar";
import { Urbanist } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import the CSS
config.autoAddCss = false; // Prevent Font Awesome from adding CSS automatically
import "../lib/fontawesome"; // Import the fontawesome setup
import Head from "next/head";

const urbanist = Urbanist({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={urbanist.className}>
        <Navbar />
        <Background />
        {children}
      </body>
    </html>
  );
}
